<div class="demo-intro">
    <header class="demo-header">
        <h1>Icons<span>&mdash;by <a href="http://glyphicons.com/">Glyphicons Halflings</a></span></h1>
    </header><!-- .demo-header -->
</div><!-- .demo-intro -->

<div class="demo">
    
    <div class="demo-description">
        <h2>Class Based</h2>
    </div>
    <div class="demo-block">
        <div class="tile-wrap">
            <div class="tile" title="icon-glass"><i class="icon-glass"></i><span>icon-glass</span></div>
            <div class="tile" title="icon-music"><i class="icon-music"></i><span>icon-music</span></div>
            <div class="tile" title="icon-search"><i class="icon-search"></i><span>icon-search</span></div>
            <div class="tile" title="icon-envelope"><i class="icon-envelope"></i><span>icon-envelope</span></div>
            <div class="tile" title="icon-heart"><i class="icon-heart"></i><span>icon-heart</span></div>
            <div class="tile" title="icon-star"><i class="icon-star"></i><span>icon-star</span></div>
            <div class="tile" title="icon-star-empty"><i class="icon-star-empty"></i><span>icon-star-empty</span></div>
            <div class="tile" title="icon-user"><i class="icon-user"></i><span>icon-user</span></div>
            <div class="tile" title="icon-film"><i class="icon-film"></i><span>icon-film</span></div>
            <div class="tile" title="icon-th-large"><i class="icon-th-large"></i><span>icon-th-large</span></div>
            <div class="tile" title="icon-th"><i class="icon-th"></i><span>icon-th</span></div>
            <div class="tile" title="icon-th-list"><i class="icon-th-list"></i><span>icon-th-list</span></div>
            <div class="tile" title="icon-ok"><i class="icon-ok"></i><span>icon-ok</span></div>
            <div class="tile" title="icon-remove"><i class="icon-remove"></i><span>icon-remove</span></div>
            <div class="tile" title="icon-zoom-in"><i class="icon-zoom-in"></i><span>icon-zoom-in</span></div>
            <div class="tile" title="icon-zoom-out"><i class="icon-zoom-out"></i><span>icon-zoom-out</span></div>
            <div class="tile" title="icon-off"><i class="icon-off"></i><span>icon-off</span></div>
            <div class="tile" title="icon-signal"><i class="icon-signal"></i><span>icon-signal</span></div>
            <div class="tile" title="icon-cog"><i class="icon-cog"></i><span>icon-cog</span></div>
            <div class="tile" title="icon-trash"><i class="icon-trash"></i><span>icon-trash</span></div>
            <div class="tile" title="icon-home"><i class="icon-home"></i><span>icon-home</span></div>
            <div class="tile" title="icon-file"><i class="icon-file"></i><span>icon-file</span></div>
            <div class="tile" title="icon-time"><i class="icon-time"></i><span>icon-time</span></div>
            <div class="tile" title="icon-road"><i class="icon-road"></i><span>icon-road</span></div>
            <div class="tile" title="icon-download-alt"><i class="icon-download-alt"></i><span>icon-download-alt</span></div>
            <div class="tile" title="icon-download"><i class="icon-download"></i><span>icon-download</span></div>
            <div class="tile" title="icon-upload"><i class="icon-upload"></i><span>icon-upload</span></div>
            <div class="tile" title="icon-inbox"><i class="icon-inbox"></i><span>icon-inbox</span></div>
            <div class="tile" title="icon-play-circle"><i class="icon-play-circle"></i><span>icon-play-circle</span></div>
            <div class="tile" title="icon-repeat"><i class="icon-repeat"></i><span>icon-repeat</span></div>
            <div class="tile" title="icon-refresh"><i class="icon-refresh"></i><span>icon-refresh</span></div>
            <div class="tile" title="icon-list-alt"><i class="icon-list-alt"></i><span>icon-list-alt</span></div>
            <div class="tile" title="icon-lock"><i class="icon-lock"></i><span>icon-lock</span></div>
            <div class="tile" title="icon-flag"><i class="icon-flag"></i><span>icon-flag</span></div>
            <div class="tile" title="icon-headphones"><i class="icon-headphones"></i><span>icon-headphones</span></div>
            <div class="tile" title="icon-volume-off"><i class="icon-volume-off"></i><span>icon-volume-off</span></div>
            <div class="tile" title="icon-volume-down"><i class="icon-volume-down"></i><span>icon-volume-down</span></div>
            <div class="tile" title="icon-volume-up"><i class="icon-volume-up"></i><span>icon-volume-up</span></div>
            <div class="tile" title="icon-qrcode"><i class="icon-qrcode"></i><span>icon-qrcode</span></div>
            <div class="tile" title="icon-barcode"><i class="icon-barcode"></i><span>icon-barcode</span></div>
            <div class="tile" title="icon-tag"><i class="icon-tag"></i><span>icon-tag</span></div>
            <div class="tile" title="icon-tags"><i class="icon-tags"></i><span>icon-tags</span></div>
            <div class="tile" title="icon-book"><i class="icon-book"></i><span>icon-book</span></div>
            <div class="tile" title="icon-bookmark"><i class="icon-bookmark"></i><span>icon-bookmark</span></div>
            <div class="tile" title="icon-print"><i class="icon-print"></i><span>icon-print</span></div>
            <div class="tile" title="icon-camera"><i class="icon-camera"></i><span>icon-camera</span></div>
            <div class="tile" title="icon-font"><i class="icon-font"></i><span>icon-font</span></div>
            <div class="tile" title="icon-bold"><i class="icon-bold"></i><span>icon-bold</span></div>
            <div class="tile" title="icon-italic"><i class="icon-italic"></i><span>icon-italic</span></div>
            <div class="tile" title="icon-text-height"><i class="icon-text-height"></i><span>icon-text-height</span></div>
            <div class="tile" title="icon-text-width"><i class="icon-text-width"></i><span>icon-text-width</span></div>
            <div class="tile" title="icon-align-left"><i class="icon-align-left"></i><span>icon-align-left</span></div>
            <div class="tile" title="icon-align-center"><i class="icon-align-center"></i><span>icon-align-center</span></div>
            <div class="tile" title="icon-align-right"><i class="icon-align-right"></i><span>icon-align-right</span></div>
            <div class="tile" title="icon-align-justify"><i class="icon-align-justify"></i><span>icon-align-justify</span></div>
            <div class="tile" title="icon-list"><i class="icon-list"></i><span>icon-list</span></div>
            <div class="tile" title="icon-indent-left"><i class="icon-indent-left"></i><span>icon-indent-left</span></div>
            <div class="tile" title="icon-indent-right"><i class="icon-indent-right"></i><span>icon-indent-right</span></div>
            <div class="tile" title="icon-facetime-video"><i class="icon-facetime-video"></i><span>icon-facetime-video</span></div>
            <div class="tile" title="icon-picture"><i class="icon-picture"></i><span>icon-picture</span></div>
            <div class="tile" title="icon-pencil"><i class="icon-pencil"></i><span>icon-pencil</span></div>
            <div class="tile" title="icon-map-marker"><i class="icon-map-marker"></i><span>icon-map-marker</span></div>
            <div class="tile" title="icon-adjust"><i class="icon-adjust"></i><span>icon-adjust</span></div>
            <div class="tile" title="icon-tint"><i class="icon-tint"></i><span>icon-tint</span></div>
            <div class="tile" title="icon-edit"><i class="icon-edit"></i><span>icon-edit</span></div>
            <div class="tile" title="icon-share"><i class="icon-share"></i><span>icon-share</span></div>
            <div class="tile" title="icon-check"><i class="icon-check"></i><span>icon-check</span></div>
            <div class="tile" title="icon-move"><i class="icon-move"></i><span>icon-move</span></div>
            <div class="tile" title="icon-step-backward"><i class="icon-step-backward"></i><span>icon-step-backward</span></div>
            <div class="tile" title="icon-fast-backward"><i class="icon-fast-backward"></i><span>icon-fast-backward</span></div>
            <div class="tile" title="icon-backward"><i class="icon-backward"></i><span>icon-backward</span></div>
            <div class="tile" title="icon-play"><i class="icon-play"></i><span>icon-play</span></div>
            <div class="tile" title="icon-pause"><i class="icon-pause"></i><span>icon-pause</span></div>
            <div class="tile" title="icon-stop"><i class="icon-stop"></i><span>icon-stop</span></div>
            <div class="tile" title="icon-forward"><i class="icon-forward"></i><span>icon-forward</span></div>
            <div class="tile" title="icon-fast-forward"><i class="icon-fast-forward"></i><span>icon-fast-forward</span></div>
            <div class="tile" title="icon-step-forward"><i class="icon-step-forward"></i><span>icon-step-forward</span></div>
            <div class="tile" title="icon-eject"><i class="icon-eject"></i><span>icon-eject</span></div>
            <div class="tile" title="icon-chevron-left"><i class="icon-chevron-left"></i><span>icon-chevron-left</span></div>
            <div class="tile" title="icon-chevron-right"><i class="icon-chevron-right"></i><span>icon-chevron-right</span></div>
            <div class="tile" title="icon-plus-sign"><i class="icon-plus-sign"></i><span>icon-plus-sign</span></div>
            <div class="tile" title="icon-minus-sign"><i class="icon-minus-sign"></i><span>icon-minus-sign</span></div>
            <div class="tile" title="icon-remove-sign"><i class="icon-remove-sign"></i><span>icon-remove-sign</span></div>
            <div class="tile" title="icon-ok-sign"><i class="icon-ok-sign"></i><span>icon-ok-sign</span></div>
            <div class="tile" title="icon-question-sign"><i class="icon-question-sign"></i><span>icon-question-sign</span></div>
            <div class="tile" title="icon-info-sign"><i class="icon-info-sign"></i><span>icon-info-sign</span></div>
            <div class="tile" title="icon-screenshot"><i class="icon-screenshot"></i><span>icon-screenshot</span></div>
            <div class="tile" title="icon-remove-circle"><i class="icon-remove-circle"></i><span>icon-remove-circle</span></div>
            <div class="tile" title="icon-ok-circle"><i class="icon-ok-circle"></i><span>icon-ok-circle</span></div>
            <div class="tile" title="icon-ban-circle"><i class="icon-ban-circle"></i><span>icon-ban-circle</span></div>
            <div class="tile" title="icon-arrow-left"><i class="icon-arrow-left"></i><span>icon-arrow-left</span></div>
            <div class="tile" title="icon-arrow-right"><i class="icon-arrow-right"></i><span>icon-arrow-right</span></div>
            <div class="tile" title="icon-arrow-up"><i class="icon-arrow-up"></i><span>icon-arrow-up</span></div>
            <div class="tile" title="icon-arrow-down"><i class="icon-arrow-down"></i><span>icon-arrow-down</span></div>
            <div class="tile" title="icon-share-alt"><i class="icon-share-alt"></i><span>icon-share-alt</span></div>
            <div class="tile" title="icon-resize-full"><i class="icon-resize-full"></i><span>icon-resize-full</span></div>
            <div class="tile" title="icon-resize-small"><i class="icon-resize-small"></i><span>icon-resize-small</span></div>
            <div class="tile" title="icon-plus"><i class="icon-plus"></i><span>icon-plus</span></div>
            <div class="tile" title="icon-minus"><i class="icon-minus"></i><span>icon-minus</span></div>
            <div class="tile" title="icon-asterisk"><i class="icon-asterisk"></i><span>icon-asterisk</span></div>
            <div class="tile" title="icon-exclamation-sign"><i class="icon-exclamation-sign"></i><span>icon-exclamation-sign</span></div>
            <div class="tile" title="icon-gift"><i class="icon-gift"></i><span>icon-gift</span></div>
            <div class="tile" title="icon-leaf"><i class="icon-leaf"></i><span>icon-leaf</span></div>
            <div class="tile" title="icon-fire"><i class="icon-fire"></i><span>icon-fire</span></div>
            <div class="tile" title="icon-eye-open"><i class="icon-eye-open"></i><span>icon-eye-open</span></div>
            <div class="tile" title="icon-eye-close"><i class="icon-eye-close"></i><span>icon-eye-close</span></div>
            <div class="tile" title="icon-warning-sign"><i class="icon-warning-sign"></i><span>icon-warning-sign</span></div>
            <div class="tile" title="icon-plane"><i class="icon-plane"></i><span>icon-plane</span></div>
            <div class="tile" title="icon-calendar"><i class="icon-calendar"></i><span>icon-calendar</span></div>
            <div class="tile" title="icon-random"><i class="icon-random"></i><span>icon-random</span></div>
            <div class="tile" title="icon-comments"><i class="icon-comments"></i><span>icon-comments</span></div>
            <div class="tile" title="icon-magnet"><i class="icon-magnet"></i><span>icon-magnet</span></div>
            <div class="tile" title="icon-chevron-up"><i class="icon-chevron-up"></i><span>icon-chevron-up</span></div>
            <div class="tile" title="icon-chevron-down"><i class="icon-chevron-down"></i><span>icon-chevron-down</span></div>
            <div class="tile" title="icon-retweet"><i class="icon-retweet"></i><span>icon-retweet</span></div>
            <div class="tile" title="icon-shopping-cart"><i class="icon-shopping-cart"></i><span>icon-shopping-cart</span></div>
            <div class="tile" title="icon-folder-close"><i class="icon-folder-close"></i><span>icon-folder-close</span></div>
            <div class="tile" title="icon-folder-open"><i class="icon-folder-open"></i><span>icon-folder-open</span></div>
            <div class="tile" title="icon-resize-vertical"><i class="icon-resize-vertical"></i><span>icon-resize-vertical</span></div>
            <div class="tile" title="icon-resize-horizontal"><i class="icon-resize-horizontal"></i><span>icon-resize-horizontal</span></div>
            <div class="tile" title="icon-hdd"><i class="icon-hdd"></i><span>icon-hdd</span></div>
            <div class="tile" title="icon-bullhorn"><i class="icon-bullhorn"></i><span>icon-bullhorn</span></div>
            <div class="tile" title="icon-bell"><i class="icon-bell"></i><span>icon-bell</span></div>
            <div class="tile" title="icon-certificate"><i class="icon-certificate"></i><span>icon-certificate</span></div>
            <div class="tile" title="icon-thumbs-up"><i class="icon-thumbs-up"></i><span>icon-thumbs-up</span></div>
            <div class="tile" title="icon-thumbs-down"><i class="icon-thumbs-down"></i><span>icon-thumbs-down</span></div>
            <div class="tile" title="icon-hand-right"><i class="icon-hand-right"></i><span>icon-hand-right</span></div>
            <div class="tile" title="icon-hand-left"><i class="icon-hand-left"></i><span>icon-hand-left</span></div>
            <div class="tile" title="icon-hand-top"><i class="icon-hand-top"></i><span>icon-hand-top</span></div>
            <div class="tile" title="icon-hand-down"><i class="icon-hand-down"></i><span>icon-hand-down</span></div>
            <div class="tile" title="icon-circle-arrow-right"><i class="icon-circle-arrow-right"></i><span>icon-circle-arrow-right</span></div>
            <div class="tile" title="icon-circle-arrow-left"><i class="icon-circle-arrow-left"></i><span>icon-circle-arrow-left</span></div>
            <div class="tile" title="icon-circle-arrow-top"><i class="icon-circle-arrow-top"></i><span>icon-circle-arrow-top</span></div>
            <div class="tile" title="icon-circle-arrow-down"><i class="icon-circle-arrow-down"></i><span>icon-circle-arrow-down</span></div>
            <div class="tile" title="icon-globe"><i class="icon-globe"></i><span>icon-globe</span></div>
            <div class="tile" title="icon-wrench"><i class="icon-wrench"></i><span>icon-wrench</span></div>
            <div class="tile" title="icon-tasks"><i class="icon-tasks"></i><span>icon-tasks</span></div>
            <div class="tile" title="icon-filter"><i class="icon-filter"></i><span>icon-filter</span></div>
            <div class="tile" title="icon-briefcase"><i class="icon-briefcase"></i><span>icon-briefcase</span></div>
            <div class="tile" title="icon-fullscreen"><i class="icon-fullscreen"></i><span>icon-fullscreen</span></div>
            <div class="tile" title="icon-dashboard"><i class="icon-dashboard"></i><span>icon-dashboard</span></div>
            <div class="tile" title="icon-paperclip"><i class="icon-paperclip"></i><span>icon-paperclip</span></div>
            <div class="tile" title="icon-heart-empty"><i class="icon-heart-empty"></i><span>icon-heart-empty</span></div>
            <div class="tile" title="icon-link"><i class="icon-link"></i><span>icon-link</span></div>
            <div class="tile" title="icon-phone"><i class="icon-phone"></i><span>icon-phone</span></div>
            <div class="tile" title="icon-pushpin"><i class="icon-pushpin"></i><span>icon-pushpin</span></div>
            <div class="tile" title="icon-euro"><i class="icon-euro"></i><span>icon-euro</span></div>
            <div class="tile" title="icon-usd"><i class="icon-usd"></i><span>icon-usd</span></div>
            <div class="tile" title="icon-gbp"><i class="icon-gbp"></i><span>icon-gbp</span></div>
            <div class="tile" title="icon-sort"><i class="icon-sort"></i><span>icon-sort</span></div>
            <div class="tile" title="icon-sort-by-alphabet"><i class="icon-sort-by-alphabet"></i><span>icon-sort-by-alphabet</span></div>
            <div class="tile" title="icon-sort-by-alphabet-alt"><i class="icon-sort-by-alphabet-alt"></i><span>icon-sort-by-alphabet-alt</span></div>
            <div class="tile" title="icon-sort-by-order"><i class="icon-sort-by-order"></i><span>icon-sort-by-order</span></div>
            <div class="tile" title="icon-sort-by-order-alt"><i class="icon-sort-by-order-alt"></i><span>icon-sort-by-order-alt</span></div>
            <div class="tile" title="icon-sort-by-attributes"><i class="icon-sort-by-attributes"></i><span>icon-sort-by-attributes</span></div>
            <div class="tile" title="icon-sort-by-attributes-alt"><i class="icon-sort-by-attributes-alt"></i><span>icon-sort-by-attributes-alt</span></div>
            <div class="tile" title="icon-unchecked"><i class="icon-unchecked"></i><span>icon-unchecked</span></div>
            <div class="tile" title="icon-expand"><i class="icon-expand"></i><span>icon-expand</span></div>
            <div class="tile" title="icon-collapse"><i class="icon-collapse"></i><span>icon-collapse</span></div>
            <div class="tile" title="icon-collapse-top"><i class="icon-collapse-top"></i><span>icon-collapse-top</span></div>
        </div>
    </div>

</div><!-- .demo -->